import { Property, Project, Lead, SupportTicket, Branch, BlogPost } from '../types';

export const initialProjects: Project[] = [
  {
    id: 'proj_001',
    title: 'Sukoon Smart Housing City',
    titleBn: 'সুকুন স্মার্ট হাউজিং সিটি',
    titleAr: 'مدينة سكون السكنية الذكية',
    slug: 'sukoon-smart-city-purbachal',
    category: 'Housing',
    location: 'Purbachal Smart City Sector 22, Dhaka',
    district: 'Purbachal',
    totalUnits: 450,
    availableUnits: 85,
    startPriceBDT: 3500000, // 35 Lakh BDT
    completionDate: 'December 2027',
    coverImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
    status: 'Under Construction',
    description: 'A 500-bigha eco-smart planned township featuring 3, 5 & 10 Katha prime housing plots with 60ft wide avenues, underground utility lines, lakeside park, central mosque, and smart security systems.',
    highlights: ['RAJA/Purbachal Express Highway Access', 'Central Mosque & Lake Park', 'Underground Electrical Cables', 'Solar Powered Streetlights', '24/7 CCTV Gated Perimeter'],
    brochureUrl: '/brochures/sukoon-smart-city.pdf',
  },
  {
    id: 'proj_002',
    title: 'Sukoon Royal Heights',
    titleBn: 'সুকুন রয়্যাল হাইটস',
    titleAr: 'سكون رويال هايتس',
    slug: 'sukoon-royal-heights-gulshan',
    category: 'Apartment',
    location: 'Gulshan Avenue, Road 68, Dhaka',
    district: 'Gulshan',
    totalUnits: 36,
    availableUnits: 6,
    startPriceBDT: 38000000, // 3.8 Crore BDT
    completionDate: 'Ready',
    coverImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    status: 'Ready',
    description: 'Ultra-luxury 3,800 sq ft & 4,500 sq ft duplex sky residences with panoramic views of Gulshan Lake, private infinity pool on roof, Smart Home automation, and Italian marble finishes.',
    highlights: ['Gulshan Lake View', 'Private Infinity Rooftop Pool', 'Smart Home Voice Control', 'Dual Lift + Service Elevator', '3 Allocated Basements Parking'],
    brochureUrl: '/brochures/sukoon-royal-heights.pdf',
  },
  {
    id: 'proj_003',
    title: 'Sukoon Green Valley Community',
    titleBn: 'সুকুন গ্রিন ভ্যালি গ্রীন কমিউনিটি',
    titleAr: 'مجمع سكون الوادي الأخضر',
    slug: 'sukoon-green-valley-uttara',
    category: 'Residential',
    location: 'Uttara Sector 18, Near Metro Station, Dhaka',
    district: 'Uttara',
    totalUnits: 180,
    availableUnits: 34,
    startPriceBDT: 12500000, // 1.25 Crore BDT
    completionDate: 'June 2026',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    status: 'Under Construction',
    description: 'Modern 3 BHK & 4 BHK residential apartments connected directly to Dhaka Metro Rail Station. Features lush botanical rooftop, gym, squash court, and children playground.',
    highlights: ['5 Min Walk to Metro Station', 'Rooftop Organic Garden', 'State-of-the-art Gymnasium', '24 Hours Backup Generator', 'Earthquake Resistant Structure'],
    brochureUrl: '/brochures/sukoon-green-valley.pdf',
  },
  {
    id: 'proj_004',
    title: 'Sukoon Commercial Hub & Plaza',
    titleBn: 'সুকুন কমার্শিয়াল হাব এন্ড প্লাজা',
    titleAr: 'مركز سكون التجاري والپلازا',
    slug: 'sukoon-commercial-hub-agrabad',
    category: 'Commercial',
    location: 'Agrabad Commercial Area, Chattogram',
    district: 'Chattogram',
    totalUnits: 90,
    availableUnits: 18,
    startPriceBDT: 25000000, // 2.5 Crore BDT
    completionDate: 'March 2027',
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    status: 'Under Construction',
    description: '22-story commercial skyscraper with grade-A corporate offices, bank vaults, luxury shopping mall, glass facade, and high-speed destination elevators.',
    highlights: ['Agrabad Commercial Heart', 'Grade-A LEED Certified Building', 'Helipad Access', 'Multi-level Automated Parking', '24/7 High Speed Fiber Optic Infrastructure'],
    brochureUrl: '/brochures/sukoon-commercial-hub.pdf',
  },
];

export const initialProperties: Property[] = [
  {
    id: 'prop_001',
    title: '5 Katha South-Facing Plot in Purbachal Sector 22',
    titleBn: 'পূর্বাচল সেক্টর ২২-এ ৫ কাঠা দক্ষিণমুখী প্লট',
    titleAr: 'قطعة أرض ٥ كاثا مطلة على الجنوب في بورباتشال القطاع ٢٢',
    projectSlug: 'sukoon-smart-city-purbachal',
    category: 'Land',
    type: '5 Katha Residential Plot',
    status: 'Ongoing',
    location: 'Sector 22, Avenue 4, Purbachal Smart City',
    district: 'Purbachal',
    address: 'Plot 412, Road 18, Sector 22, Purbachal, Dhaka',
    priceBDT: 4500000,
    priceFormatted: '৳ 45.00 Lakh (د.ك 11.6K)',
    areaSqFt: 3600,
    areaUnit: 'Katha',
    facing: 'South Facing',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1592595896551-12b371d546d5?auto=format&fit=crop&w=1000&q=80',
    ],
    floorPlans: [
      {
        id: 'fp_1',
        title: 'Proposed Duplex Villa Layout',
        size: '3600 Sq Ft Ground Area',
        rooms: '5 Beds, 6 Baths, Private Pool',
        image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80',
      },
    ],
    nearby: [
      { name: 'Purbachal International School', category: 'School', distance: '0.4 km' },
      { name: 'Kuwait Bangladesh Friendship Hospital', category: 'Hospital', distance: '1.2 km' },
      { name: 'Purbachal Central Mosque', category: 'Mosque', distance: '0.2 km' },
      { name: '300 Feet Expressway Interchange', category: 'Transport', distance: '1.5 km' },
    ],
    description: 'Ready to register south-facing 5 Katha plot on 60ft wide road in Purbachal Smart City. Gas connection line installed, electricity grid ready, immediately suitable for duplex house construction.',
    features: ['60 Ft Avenue Access', 'WASA Water & Gas Lines', 'Demarcated Boundary Pillars', 'Corner Demarcation', 'RAJA Approved Layout'],
    mapCoords: { lat: 23.834, lng: 90.521 },
    isFeatured: true,
    isPremium: true,
    dateAdded: '2026-06-15',
  },
  {
    id: 'prop_002',
    title: 'Luxury 3,800 Sq Ft Lakeview Duplex in Gulshan 2',
    titleBn: 'গুলশান ২-এ ৩,৮০০ স্কয়ার ফিটের লেকভিউ ডুপ্লেক্স অ্যাপার্টমেন্ট',
    titleAr: 'شقة دوبلكس فاخرة ٣٨٠٠ قدم مربع مطلة على البحيرة في غولشان',
    projectSlug: 'sukoon-royal-heights-gulshan',
    category: 'Apartment',
    type: '4 BHK Luxury Duplex',
    status: 'Ready to Move',
    location: 'Gulshan Avenue, Road 68, Gulshan 2',
    district: 'Gulshan',
    address: 'Level 12 & 14, Sukoon Royal Tower, Gulshan 2, Dhaka',
    priceBDT: 42000000,
    priceFormatted: '৳ 4.20 Crore (د.ك 108.7K)',
    areaSqFt: 3800,
    areaUnit: 'sq ft',
    bed: 4,
    bath: 5,
    parking: 3,
    facing: 'North-East Lake Facing',
    yearBuilt: 2025,
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1000&q=80',
    ],
    floorPlans: [
      {
        id: 'fp_2a',
        title: 'Lower Level Duplex Living & Dining',
        size: '2000 Sq Ft',
        rooms: 'Grand Foyer, Living Room, Guest Bed, Kitchen',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'fp_2b',
        title: 'Upper Level Master Suites & Jacuzzi Terrace',
        size: '1800 Sq Ft',
        rooms: 'Master Suite, 2 Family Bedrooms, Private Study',
        image: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?auto=format&fit=crop&w=800&q=80',
      },
    ],
    nearby: [
      { name: 'American International School Dhaka (AISD)', category: 'School', distance: '0.8 km' },
      { name: 'United Hospital Gulshan', category: 'Hospital', distance: '1.0 km' },
      { name: 'Gulshan Society Mosque', category: 'Mosque', distance: '0.5 km' },
      { name: 'Unimart Gulshan 2', category: 'Shopping', distance: '0.3 km' },
    ],
    description: 'Magnificent 4 Bedroom sky penthouse overlooking Gulshan Lake. Equipped with Italian Kohler fittings, solid teak doors, private plunge jacuzzi balcony, and 24/7 full load generator backup.',
    features: ['Panoramic Lake View', 'Jacuzzi Balcony', 'Smart Lock Fingerprint Access', 'Servant Room + Bath', 'German Hacker Fitted Kitchen'],
    mapCoords: { lat: 23.792, lng: 90.415 },
    isFeatured: true,
    isPremium: true,
    dateAdded: '2026-07-01',
  },
  {
    id: 'prop_003',
    title: 'Modern 2,150 Sq Ft 3-BHK Flat in Uttara Sector 18',
    titleBn: 'উত্তরা সেক্টর ১৮-এ আধুনিক ২,১৫০ স্কয়ার ফিট ৩-বিএইচকে ফ্ল্যাট',
    titleAr: 'شقة حديثة ثلاث غرف ٢١٥٠ قدم مربع في أوتارا القطاع ١٨',
    projectSlug: 'sukoon-green-valley-uttara',
    category: 'Apartment',
    type: '3 BHK Apartment',
    status: 'Ongoing',
    location: 'Uttara Sector 18, Near Metro Rail Depot',
    district: 'Uttara',
    address: 'Apt 8B, Sukoon Green Valley, Sector 18, Uttara, Dhaka',
    priceBDT: 15500000,
    priceFormatted: '৳ 1.55 Crore (د.ك 40.1K)',
    areaSqFt: 2150,
    areaUnit: 'sq ft',
    bed: 3,
    bath: 4,
    parking: 1,
    facing: 'South-West Facing',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80',
    ],
    floorPlans: [
      {
        id: 'fp_3',
        title: '3-BHK Standard Unit Layout',
        size: '2150 Sq Ft',
        rooms: '3 Bed, 4 Bath, 3 Balconies, Servant Room',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
      },
    ],
    nearby: [
      { name: 'Uttara Sector 18 Metro Station', category: 'Transport', distance: '0.2 km' },
      { name: 'Uttara High School & College', category: 'School', distance: '1.1 km' },
      { name: 'Labaid Hospital Uttara', category: 'Hospital', distance: '1.5 km' },
    ],
    description: 'Spacious 3 bed family flat in the booming Uttara Sector 18 metro area. Cross-ventilation layout with 3 wide balconies, dedicated child play area, and solar power water heating.',
    features: ['Near Metro Rail', 'Rooftop Community Hall', 'Children Playground', 'Fire Safety Sprinklers', 'Double Glazed Soundproof Windows'],
    mapCoords: { lat: 23.875, lng: 90.389 },
    isFeatured: true,
    isPremium: false,
    dateAdded: '2026-07-10',
  },
  {
    id: 'prop_004',
    title: 'Prime 1,850 Sq Ft Commercial Space in Agrabad Tower',
    titleBn: 'চট্টগ্রাম আগ্রাবাদ টাওয়ারে ১,৮৫০ স্কয়ার ফিট বাণিজ্যিক স্পেস',
    titleAr: 'مساحة تجارية متميزة ١٨٥٠ قدم مربع في برج أغراباد',
    projectSlug: 'sukoon-commercial-hub-agrabad',
    category: 'Commercial',
    type: 'Grade-A Office Floor',
    status: 'Ongoing',
    location: 'Agrabad Commercial Area, Chattogram',
    district: 'Chattogram',
    address: 'Level 7, Sukoon Commercial Plaza, Agrabad, Chattogram',
    priceBDT: 29500000,
    priceFormatted: '৳ 2.95 Crore (د.ك 76.4K)',
    areaSqFt: 1850,
    areaUnit: 'sq ft',
    parking: 2,
    facing: 'Main Avenue Facing',
    images: [
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1000&q=80',
    ],
    floorPlans: [
      {
        id: 'fp_4',
        title: 'Open Executive Office Floor Plan',
        size: '1850 Sq Ft',
        rooms: 'CEO Suite, 2 Conference Rooms, Open Workstations for 25',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
      },
    ],
    nearby: [
      { name: 'Chattogram Port Authority HQ', category: 'Transport', distance: '1.8 km' },
      { name: 'Dutch-Bangla Bank Main Branch', category: 'Bank', distance: '0.1 km' },
      { name: 'Hotel Agrabad', category: 'Shopping', distance: '0.3 km' },
    ],
    description: 'Corporate office space with floor-to-ceiling double tempered glass in Chattogram financial heart. Ideal for Multinational Corporations, Banks, Freight Forwarders, and IT companies.',
    features: ['High Speed Lifts', 'Centralized HVAC Air Conditioning', 'VRF Climate Control', 'Automated Fire Suppression'],
    mapCoords: { lat: 22.324, lng: 91.815 },
    isFeatured: false,
    isPremium: true,
    dateAdded: '2026-07-12',
  },
  {
    id: 'prop_005',
    title: 'Beachfront Holiday Condo in Cox’s Bazar Marine Drive',
    titleBn: 'কক্সবাজার মেরিন ড্রাইভের বিচফ্রন্ট হলিডে কনডোমিনিয়াম',
    titleAr: 'شقة شاطئية للعطلات في طريق مارين درايف كوكس بازار',
    projectSlug: 'sukoon-horizon-beach-resort',
    category: 'Housing',
    type: 'Resort Condo Apartment',
    status: 'Upcoming',
    location: 'Inani Beach, Marine Drive, Cox’s Bazar',
    district: 'Cox\'s Bazar',
    address: 'Suite 504, Sukoon Horizon Beach Resort, Marine Drive, Cox’s Bazar',
    priceBDT: 18000000,
    priceFormatted: '৳ 1.80 Crore (د.ك 46.6K)',
    areaSqFt: 1400,
    areaUnit: 'sq ft',
    bed: 2,
    bath: 2,
    parking: 1,
    facing: 'Sea Facing',
    images: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80',
    ],
    floorPlans: [
      {
        id: 'fp_5',
        title: 'Sea Facing Suite Layout',
        size: '1400 Sq Ft',
        rooms: '2 Bedroom, Private Sunset Balcony, Kitchenette',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
      },
    ],
    nearby: [
      { name: 'Inani Coral Beach', category: 'Transport', distance: '0.1 km' },
      { name: 'Cox’s Bazar International Airport', category: 'Transport', distance: '18.0 km' },
    ],
    description: 'Invest in Bangladesh premier oceanfront resort project. Features guaranteed annual rental return pool managed by Sukoon Hospitality division, sunset deck, and private beach access.',
    features: ['Direct Beach Access', 'Rental Income Pool', 'Infinity Pool overlooking Bay of Bengal', 'Spa & Wellness Center'],
    mapCoords: { lat: 21.242, lng: 92.052 },
    isFeatured: true,
    isPremium: true,
    dateAdded: '2026-07-20',
  },
];

export const initialLeads: Lead[] = [
  {
    id: 'ld_001',
    name: 'Dr. Shahriar Rahman',
    email: 'shahriar.med@gmail.com',
    phone: '+880 1712-334455',
    propertyInterest: '5 Katha Plot in Purbachal Sector 22',
    budgetBDT: 5000000,
    districtInterest: 'Purbachal',
    status: 'Site Visit Scheduled',
    assignedTo: 'Tanvir Hossain (Sr. Executive)',
    notes: ['Interested in cash payment discount', 'Scheduled site visit for next Friday at 10 AM'],
    source: 'Website Form',
    createdAt: '2026-07-28',
  },
  {
    id: 'ld_002',
    name: 'Mrs. Nusrat Jahan',
    email: 'nusrat.jahan@yahoo.com',
    phone: '+880 1819-887766',
    propertyInterest: '3 BHK Flat in Uttara Sector 18',
    budgetBDT: 16000000,
    districtInterest: 'Uttara',
    status: 'Negotiation',
    assignedTo: 'Farhana Akhter (Manager)',
    notes: ['Bank loan approval in progress from DBBL', 'Requesting 5% down payment option'],
    source: 'Facebook',
    createdAt: '2026-07-29',
  },
  {
    id: 'ld_003',
    name: 'Engr. Mahmudul Hasan',
    email: 'mhasan.engr@gmail.com',
    phone: '+880 1911-223344',
    propertyInterest: 'Luxury Lakeview Duplex in Gulshan 2',
    budgetBDT: 40000000,
    districtInterest: 'Gulshan',
    status: 'Closed (Won)',
    assignedTo: 'Rayhanul Mobarak (Director)',
    notes: ['bKash initial token booking paid', 'MOU Deed executed'],
    source: 'WhatsApp',
    createdAt: '2026-07-25',
  },
];

export const initialTickets: SupportTicket[] = [
  {
    id: 'tkt_101',
    ticketCode: 'TKT-2026-8801',
    userEmail: 'client.hasan@gmail.com',
    userName: 'Hasan Al Mamun',
    subject: 'Request for Plot Demarcation Certificate Copy',
    category: 'Booking',
    priority: 'Medium',
    status: 'In Progress',
    messages: [
      { sender: 'Hasan Al Mamun', text: 'Dear Sukoon team, I paid the 2nd installment for Plot 412. Please send the demarcation certificate.', timestamp: '2026-07-30 11:20 AM' },
      { sender: 'Sukoon Support', text: 'Hello Mr. Hasan, thank you for reaching out. We have notified our Purbachal site engineer. The document will be emailed shortly.', timestamp: '2026-07-30 02:15 PM' },
    ],
    createdAt: '2026-07-30',
  },
];

export const initialBranches: Branch[] = [
  {
    id: 'br_01',
    name: 'Dhaka Head Office (Gulshan Tower)',
    city: 'Dhaka',
    address: 'Sukoon Corporate Tower, Level 14, Gulshan Avenue 2, Dhaka 1212',
    phone: '+880 1913-780386',
    email: 'sukoonpropertiesltd@gmail.com',
    manager: 'Rayhanul Mobarak (Director)',
  },
  {
    id: 'br_02',
    name: 'Purbachal Project Experience Center',
    city: 'Purbachal',
    address: 'Sector 22 Main Avenue, Purbachal Smart City, Dhaka',
    phone: '+880 1800-785666',
    email: 'purbachal@sukoonproperties.com',
    manager: 'Rafiqul Islam',
  },
  {
    id: 'br_03',
    name: 'Chattogram Commercial Branch',
    city: 'Chattogram',
    address: 'Agrabad Commercial Area, World Trade Center Road, Chattogram',
    phone: '+880 1900-554433',
    email: 'chattogram@sukoonproperties.com',
    manager: 'Kazi Nazmul',
  },
  {
    id: 'br_04',
    name: 'Sylhet Regional Office',
    city: 'Sylhet',
    address: 'Zindabazar Commercial Center, Level 4, Sylhet',
    phone: '+880 1600-112233',
    email: 'sylhet@sukoonproperties.com',
    manager: 'Tariq Al-Syed',
  },
];

export const initialBlogs: BlogPost[] = [
  {
    id: 'blog_1',
    slug: 'purbachal-smart-city-investment-guide-2026',
    title: 'Why Purbachal Smart City is the #1 Real Estate Investment in Bangladesh 2026',
    titleBn: 'কেন পূর্বাচল স্মার্ট সিটি ২০২৬ সালে বাংলাদেশের ১ নম্বর রিয়েল এস্টেট বিনিয়োগ',
    excerpt: 'An in-depth analysis of property appreciation, RAJA masterplan, and 300-ft expressway connectivity driving high yields in Purbachal.',
    content: 'Purbachal Smart City represents the future of urban Bangladesh. With planned underground electricity grid, smart traffic management, lakes, and international financial district, land prices have seen 25% annual appreciation...',
    category: 'Market Trends',
    author: 'Rayhanul Mobarak',
    date: 'July 24, 2026',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'blog_2',
    slug: 'dhaka-metro-rail-impact-on-uttara-flat-prices',
    title: 'How Dhaka Metro Rail Line 6 Transformed Uttara & Mirpur Housing Demand',
    titleBn: 'ঢাকা মেট্রো রেল লাইন ৬ যেভাবে উত্তরা ও মিরপুরের ফ্ল্যাটের মূল্য বৃদ্ধি করেছে',
    excerpt: 'Apartments within 500 meters of Metro stations are witnessing up to 35% premium rental yields.',
    content: 'Commute times from Uttara Sector 18 to Motijheel have reduced from 2.5 hours to 38 minutes. Homebuyers are prioritizing transit-oriented developments...',
    category: 'Buying Tips',
    author: 'Tanvir Hossain',
    date: 'July 18, 2026',
    readTime: '4 min read',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
  },
];
